arduino/setup-task

- .github/workflows/check-license.yml
- LICENSE
- README.md
- __tests__/main.test.ts
- package.json
- src/installer.ts
- src/main.ts
Whenever one of the recognized license file names are modified in the repository, the workflow runs [licensee](https://github.com/licensee/licensee) to check whether the license can be recognized and whether it is of the expected type.
> Add CI workflow to check the license file

- .github/workflows/test-integration.yml
- README.md
- package.json
This provides some end to end tests to provide verification that the action code works within the GitHub Actions framework.
> Add an integration test CI workflow

- .github/workflows/check-action-metadata-task.yml
- README.md
- Taskfile.yml
- action.yml
On every push or pull request that affects the [action.yml](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) GitHub Actions metadata file, and periodically, validate action.yml against [its JSON schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json).
> Add CI workflow to validate action.yml

- .github/workflows/setup-taskflile.yml
The action was moved to the root of the repository during the migration, so the "setup-taskflile" [sic] workflow must be
updated accordingly.
> Update the "setup-taskflile" workflow for new repository structure

- .codespellrc
- .github/workflows/spell-check-task.yml
- README.md
- Taskfile.yml
- poetry.lock
- pyproject.toml
On every push, pull request, and periodically, use [the `codespell-project/actions-codespell` action](https://github.com/codespell-project/actions-codespell) to check for commonly misspelled words.
In the event of a false positive, the problematic word should be added, in all lowercase, to the `ignore-words-list` field of `./.codespellrc`. Regardless of the case of the word in the false positive, it must be in all lowercase in the ignore list. The ignore list is comma-separated with no spaces.
> Add CI workflow to check for commonly misspelled words

- CONTRIBUTING.md
- README.md
This information is not of interest to those who only want to use the action, so it is not appropriate for the readme.
> Move development documentation to CONTRIBUTING.md

- .github/workflows/check-npm.yml
- package-lock.json
On every push and pull request that affects relevant files, and periodically:
- Validate package.json against [its JSON schema](https://json.schemastore.org/package.json).
- Check for forgotten manifest updates.
> Add CI workflow to check project's npm configuration

- README.md
History shows that the previous description "latest stable version of Task" is not likely to be accurate over time.
Better to just be honest about what the action does.
> Change description of default version example snippet to be realistic

- .github/workflows/setup-taskflile.yml
- .github/workflows/test-integration.yml
- CONTRIBUTING.md
- dist/index.js
The previous development policy was to only repackage on each release. This prevented contributors from doing casual beta
testing by simply referencing the action as `arduino/setup-taskfile@main` in a workflow.
This policy change is implemented via:
- Update development and release workflow documentation.
- Add a CI job to check for forgotten packaging.
- Repackage the current code.
- Adjust the integration testing workflow to account for new policy.
> Change development policy to repackaging on every code change

- .github/workflows/check-npm.yml
- .github/workflows/check-tsconfig.yml
- README.md
On every push or pull request that affects the repository's [TypeScript configuration files](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), and periodically, validate them
against [their JSON schema](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#schema).
> Add CI workflow to validate tsconfig.json files

- .github/workflows/check-markdown-task.yml
- .markdown-link-check.json
- .markdownlint.yml
- README.md
- Taskfile.yml
On every push and pull request that affects relevant files, and periodically, check the repository's Markdown files for
problems:
- Use [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) to check for common problems and formatting.
- Use [markdown-link-check](https://github.com/tcort/markdown-link-check) to check for broken links.
Arduino's Markdown style is defined by the `.markdownlint.yml` file.
In the event the repository contains externally maintained Markdown files, markdownlint can be configured to ignore them via a `.markdownlintignore` file:
https://github.com/igorshubovych/markdownlint-cli#ignoring-files
markdown-link-check is configured via the `.markdown-link-check.json` file:
https://github.com/tcort/markdown-link-check#config-file-format
> Add CI workflow to check Markdown files for problems

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/check-action-metadata-task.yml
- .github/workflows/check-markdown-task.yml
- .github/workflows/check-typescript-task.yml
- .github/workflows/test-integration.yml
- CONTRIBUTING.md
- README.md
- __tests__/main.test.ts
- action.yml
- dist/index.js
- package-lock.json
- package.json
- pyproject.toml
- src/installer.ts
- src/main.ts
[The Task documentation](https://taskfile.dev/#/) consistently refers to the tool as "Task". Taskfile is the term used for Task's configuration file.
This action is setting up the Task tool, not setting up the Task configuration file, so "arduino/setup-task" is more
appropriate than "arduino/setup-taskfile".
> Change project name to "arduino/setup-task"

- .github/workflows/check-license.yml
- .github/workflows/check-prettier-formatting-task.yml
- .github/workflows/setup-taskflile.yml
- .prettierignore
- CONTRIBUTING.md
- README.md
- Taskfile.yml
- action.yml
- jest.config.js
- package.json
- tsconfig.json
- Use Prettier to format all supported file types.
- Use Task as runner for Prettier.
- Move formatting CI to dedicated workflow.
> Refresh formatting infrastructure

- action.yml
- dist/index.js
- src/main.ts
The default value of the `version` input is defined in the action metadata, so having another default setting in the code
is purely redundant and doubles the maintenance effort required on every major release of Task (note that they already
went out of sync).
> Remove redundant default version code

- .github/dependabot.yml
Even though the project's current use of Python is insignificant, we already have the infrastructure in place and
Dependabot has been very useful for the other dependencies, so it makes sense to use it for everything.
Reference:
https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#about-the-dependabotyml-file
---
- https://github.com/per1234/setup-task/pull/1
- https://github.com/per1234/setup-task/pull/15
> Configure Dependabot for Python dependencies

- .github/workflows/check-tsconfig.yml
At the time the "Check TypeScript Configuration" workflow was created, the eslint proposal was still pending, so only
tsconfig.json was validated in the initial implementation of the workflow.
Now that the project contains two tsconfig files and the infrastructure is in place to easily validate any number of
these files, it might as well be used to the fullest extent.
> Validate tsconfig.eslint.json

- .github/workflows/check-npm.yml
- .github/workflows/test-typescript-task.yml
- README.md
- Taskfile.yml
- Meaningful and accurate name
- Readme badge
- Cross-platform
- Don't use unstable development versions of utility actions
- Use modern `actions/setup-node` API
- Use relevant Node.js version
- Use path filters to avoid unnecessary runs
- Add convenience triggers
> Bring test workflow into compliance with best practices

- .github/workflows/test-typescript-task.yml
- dist/index.js
- src/installer.ts
`tempDirectory` is not used anywhere in the code and was causing the linting of imports to fail.
> Remove unused `tempDirectory` definition code

- .github/workflows/check-action-metadata-task.yml
- .github/workflows/check-markdown-task.yml
- .github/workflows/check-npm.yml
- .github/workflows/check-prettier-formatting-task.yml
- .github/workflows/check-typescript-task.yml
- .github/workflows/spell-check-task.yml
- .github/workflows/test-typescript-task.yml
This useful action is an integral part of the project's own CI system. Now that it has a dedicated repository and a new name, the CI
workflows must be updated to use the latest release version of the action.
> Use new action name in CI workflows

- dist/index.js
- src/installer.ts
Currently, if users set a version range (e.g. `3.x`) they have no way to understand what Task version their CI actually ran by looking only at its logs. 
Printing the installed version is something other similar tools do (e.g. [actions/setup-go](https://github.com/actions/setup-go/blob/v2.1.4/src/main.ts#L35)) and that can be very useful in case of debugging.
As an example, in https://github.com/arduino/arduino-cli/pull/1576 it was hard to understand what broke the CI as from the logs it seemed that nothing had changed.
> Print installed Task version

- .codespellrc
- .markdownlintignore
- Taskfile.yml
- package-lock.json
Currently, if we use `task fix` or `task check` with the project's directory in an unclean state execution takes a lot of time and/or returns a lot of errors as some linters process the `node_modules` directory.
Note: I had to update the npm lockfile as the CI was broken otherways (check [here](https://github.com/arduino/setup-task/runs/4397709018?check_suite_focus=true)).
> Ignore node_modules on fixers and linters

- .github/workflows/check-npm.yml
- .github/workflows/check-tsconfig.yml
- .github/workflows/sync-labels.yml
The [`carlosperate/download-file-action` action](https://github.com/carlosperate/download-file-action) is used in the GitHub Actions workflows as a convenient way to download external resources.
A [major version ref](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management) has been added to that repository:
https://github.com/carlosperate/download-file-action/releases/tag/v1
It will always point to the latest release of the "1" major version series.
This means it is no longer necessary to do a full pin of the action version in use as before.
Use of the major version ref will cause the workflow to use a stable version of the action, while also benefiting from ongoing development to the action up until such time as a new major release of an …
> Use major version ref of `carlosperate/download-file-action`

- .github/workflows/check-npm.yml
- .github/workflows/check-typescript-task.yml
- .github/workflows/test-typescript-task.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
The test runner CI workflow was using Node.js 12.x, which reaches EOL 2022-04-30.
Other workflows did not specify a Node.js version, meaning they used whatever was installed on the GitHub Actions runner.
It will be best to define a specific version series for use and use that throughout the infrastructure and development.
16.x is [the newest version in LTS status](https://nodejs.org/en/about/releases/). LTS seems the most appropriate choice for the needs of this project.
> Update Node.js version used for development and CI to 16

- .github/dependabot.yml
The project has a dependency on the `@types/node` package. That package follows the major version of Node.js.
https://stackoverflow.com/questions/42035263/relationship-between-the-version-of-node-js-and-the-version-of-types-node
Since we are now using Node.js 16.x for the development of the project, we must also use the ^16.x series of `@types/node`.
Since there are 17.x versions of the `@types/node` package available, Dependabot would submit unwanted PRs to bump the dependency to those versions (e.g., https://github.com/arduino/setup-task/pull/295). This configuration prevents that. Dependabot will continue to submit PRs for bumps to any new minor or patch releases made within the current major version series.
Since this configuration prevents Dependabot from submitting major version …
> Prevent inappropriate `@types/node` bumps from Dependabot

- .github/workflows/check-npm.yml
A "Check npm" GitHub Actions workflow is used to check for problems with the repository's npm configuration files.
This workflow is based on one hosted and maintained in a repository dedicated to a collection of such reusable assets.
Several enhancements have been made to the upstream file, but those had not yet been pulled into this repository:
- Restrict permissions of `GITHUB_TOKEN`
https://github.com/per1234/.github/commit/110526423b2fb08f0145f604bcc11c3d2ee4fe77
- Install referenced schema
https://github.com/per1234/.github/commit/61d9f9b8e23d17917ffbdfee3fa1b89ecbc673f8
> Sync "Check npm" workflow with upstream

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/feature-request.yml
High quality feedback via GitHub issues is a very valuable contribution to the project. It is important to make the issue creation and management process as efficient as possible for the contributors, maintainers, and developers.
Issue templates are helpful to the maintainers and developers because it establishes a standardized framework for the issues and encourages the contributors to provide the essential information.
The contributor is now presented with [a web form](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) when creating an issue. This consists of multi-line input fields that have the same formatting, preview, and attachment capabilities as the standard GitHub …
> Use form-based issue templates

- .github/workflows/check-npm.yml
The "Check npm" GitHub Actions workflow validates the repository's `package.json` npm manifest file against its JSON schema to catch any problems with its data format.
In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The `package.json` schema was recently updated to share resources with the `ava.json` schema, which caused the validation to start failing:
```text
schema /home/runner/work/_temp/json-schema/package-json-schema.json is invalid
error: can't resolve reference https://json.schemastore.org/ava.json from id #
```
The solution is to configure the workflow to download that schema as well and also to provide its path to the avj-cli validator via an `-r` flag.
> Install referenced schema in "Check npm" workflow

- .markdown-link-check.json
The link check job of the "Check Markdown" workflow has had frequent intermittent spurious failures recently, caused by links under the `docs.github.com` domain returning [403 HTTP status](https://en.wikipedia.org/wiki/HTTP_403).
Others experiencing the same problem reported that they were able to work around the problem by providing a custom [`Accept-Encoding` HTTP request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding). Although I was not able to find any explanation of why, it does appear to resolve the problem.
Since the problem seems to be permanent and the only other workarounds I have identified are unappealing (considering links returning 403 statuses alive, or ignoring all `docs.github.com` links), I think it is worth a try.
> Configure link check to use `Accept-Encoding` header for docs.github.com links

- .github/workflows/check-npm.yml
The "Check npm" GitHub Actions workflow validates the repository's `package.json` npm manifest file against its JSON
schema to catch any problems with its data format.
In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The
`package.json` schema was recently updated to share resources with the `.stylelintrc` and semantic-release configuration
schemas, which caused the validation to
start failing:
```
schema /home/runner/work/_temp/json-schema/package-json-schema.json is invalid
error: can't resolve reference https://json.schemastore.org/stylelintrc.json from id #
```
The solution is to configure the workflow to download that schema as well and also to provide its path to the avj-cli
validator via an `-r` flag.
> Install referenced schemas in "Check npm" workflow

- .github/workflows/check-npm-dependencies-task.yml
- .licensed.yml
- .licenses/npm/@actions/core.dep.yml
- .licenses/npm/@actions/exec.dep.yml
- .licenses/npm/@actions/http-client.dep.yml
- .licenses/npm/@actions/io.dep.yml
- .licenses/npm/@actions/tool-cache.dep.yml
- .licenses/npm/call-bind.dep.yml
- .licenses/npm/function-bind.dep.yml
- .licenses/npm/get-intrinsic.dep.yml
- .licenses/npm/has-symbols.dep.yml
- .licenses/npm/has.dep.yml
- .licenses/npm/lru-cache.dep.yml
- .licenses/npm/object-inspect.dep.yml
- .licenses/npm/qs.dep.yml
- .licenses/npm/semver-6.3.0.dep.yml
- .licenses/npm/semver-7.3.7.dep.yml
- .licenses/npm/side-channel.dep.yml
- .licenses/npm/tunnel.dep.yml
- .licenses/npm/typed-rest-client.dep.yml
- .licenses/npm/underscore.dep.yml
- .licenses/npm/uuid-3.3.2.dep.yml
- .licenses/npm/uuid-8.3.2.dep.yml
- .licenses/npm/yallist.dep.yml
- .prettierignore
- CONTRIBUTING.md
- README.md
- Taskfile.yml
- package-lock.json
- package.json
A task and GitHub Actions workflow are provided here for checking the license types of [**npm**](https://www.npmjs.com/)-managed project dependencies.
On every push and pull request that affects relevant files, the CI workflow will use [**Licensed**](https://github.com/github/licensed) to check:
- If the dependency licenses cache is up to date
- If any of the project's dependencies have an unapproved license type.
Approval can be based on:
- [Allowed license type](https://github.com/github/licensed/blob/master/docs/configuration/allowed_licenses.md)
- [Individual dependency](https://github.com/github/licensed/blob/master/docs/configuration/reviewing_dependencies.md)
> Add CI workflow to check for unapproved npm dependency licenses

- Taskfile.yml
The `ts:validate` task validates the repository's TypeScript configuration files against [their JSON schema](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#schema).
The `tsconfig.json` file contains comments, which are not supported by the version of [the JSON schema validator tool](https://ajv.js.org/packages/ajv-cli.html) in use. The comments are removed by the task and the cleaned data written to a temporary file.
Previously, the wrong [taskfile variable](https://taskfile.dev/usage/#dynamic-variables) was used in the command that generates the filename of that temporary file, resulting in it having a different filename than intended. This has no functional effect on the validation results, which are solely based on the content of the file and not its name, however, it …
> Use appropriate file name for TypeScript config file when validating

- action.yml
GitHub is migrating all actions from Node 12 to Node 16 and is raising warnings for actions still using Node 12. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Update the version accordingly.
> Bump Node version from 12 to 16

- dist/index.js
- src/installer.ts
Previously, the action could only install [**Task**](https://taskfile.dev/) when the GitHub Actions runner the [workflow](https://docs.github.com/actions/using-workflows/about-workflows) job was running on had an [x86-64](https://en.wikipedia.org/wiki/X86-64) or [i386](https://en.wikipedia.org/wiki/I386) architecture.
Since the GitHub-hosted runners are currently all x86-64, that is sufficient for most users. However, it is also possible to use GitHub actions with [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) of other architectures. [**Task** builds](https://github.com/go-task/task/releases) are available for more architectures, so the action's code unnecessarily limited its utility.
Support for all architectures with …
> Add support for all Task build architectures

- .github/workflows/check-action-metadata-task.yml
- .github/workflows/check-npm-dependencies-task.yml
- .github/workflows/check-prettier-formatting-task.yml
- .github/workflows/check-typescript-task.yml
- .github/workflows/test-typescript-task.yml
- CONTRIBUTING.md
- Taskfile.yml
- action.yml
- package-lock.json
- package.json
Warnings are now being sent out due the deprecation of node16, node20 should be used for Github Actions.
This PR also update the `npm:validate` task based on @alessio-perugini's [comment below](https://github.com/arduino/setup-task/pull/919#issuecomment-1921243793).
> Bump node from 16 to 20

- .github/workflows/test-integration.yml
- __tests__/main.test.ts
- __tests__/testdata/tags.json
The unit and integration tests install various versions of Task.
The GitHub Actions macos-latest runner was recently changed from using x86 machines to Apple Silicon/ARM machines:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Task is now built for both architectures. However, this was not done for the older versions of Task previously used for the tests. The runner architecture switch caused the tests to start failing spuriously on the macos-latest GitHub Actions workflow run jobs:
https://github.com/arduino/setup-task/actions/runs/10205578962/job/28236648855#step:5:30
```text
FAIL __tests__/main.test.ts
installer tests
✕ Downloads version of Task if no matching …
```
> Use versions of Task with Apple Silicon builds in tests

- .github/workflows/check-npm-dependencies-task.yml
This GitHub Actions action is used by the dependency license check workflow to install the [**Licensed**](https://github.com/licensee/licensed) tool in the runner workspace.
The action has a convoluted history of ownership: the repository was originally owned by GitHub user [`jonabc`](https://github.com/jonabc). It was later transferred to the [`github`](https://github.com/github) organization. Then GitHub abandoned the project, archiving the repository. The [`licensee`](https://github.com/licensee) organization has now created a hard fork of the action, which is recommended in [the readme of the `github/setup-licensed` repository](https://github.com/github/setup-licensed#setup-licensed).
The `licensee` organization has also taken over the management of the **Licensed** tool, and their …
> Use maintained fork of "setup-licensed" action in dependency license check workflow

- .github/workflows/check-npm-dependencies-task.yml
The [**Licensed**](https://github.com/licensee/licensed) tool is used to check the project's compatibility with the licensing of its dependencies.
This tool is installed by the dependency license check GitHub Actions workflow using the [**licensee/setup-licensed**](https://github.com/licensee/setup-licensed) GitHub Actions action. This action attempts the installation according to the following procedure:
1. Install [the Ruby gem](https://rubygems.org/gems/licensed).
2. If gem installation fails, install the pre-built executable from the GitHub release asset in the `licensee/licensed` repo.
Previously, the first of these installation methods was failing:
```text
/usr/bin/gem install licensed -v 3.9.1
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write …
```
> Configure dependency license check workflows to allow "Licensed" install via Gem

- .github/workflows/check-npm-dependencies-task.yml
The version of the [**Licensed**](https://github.com/licensee/licensed) tool for use in the GitHub Actions workflow is defined via the **github/setup-licensed** action's `version` input.
Previously the action was configured to install version 3.x of the action. That version is significantly outdated. The workflow is hereby updated to use the latest version of **Licensed**.
> Bump "Licensed" version in dependency license check workflow

- .licenses/npm/function-bind.dep.yml
- .licenses/npm/inherits.dep.yml
- .licenses/npm/semver-6.3.0.dep.yml
- .licenses/npm/semver-7.7.1.dep.yml
The [**Licensed**](https://github.com/licensee/licensed) tool is used to check for incompatible licenses in the project dependencies. The tool relies on a cache of metadata stored in the repository.
An older version of **Licensed** was in use at the time the cache was established. There are some minor differences in the format of the metadata generated by the version of **Licensed** currently in use.
Even though there is no technical significance to the format differences, they are disruptive in that they result in irrelevant diffs in specific metadata files when they are regenerated after a dependency bump. Rather than dealing with these diffs over time, it will be best to instead update the metadata to the new format comprehensively.
> Update format of dependency license metadata
